# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

WorkDay.destroy_all

WorkDay.create!([
  { name: 'Monday', short_name: 'MON' },
  { name: 'Tuesday', short_name: 'TUE' },
  { name: 'Wednesday', short_name: 'WED' },
  { name: 'Thursday', short_name: 'THU' },
  { name: 'Friday', short_name: 'FRI' }
])

p "Created #{WorkDay.count} work days"

Language.destroy_all

languages = Language.create([
  { name: 'English', code: 'EN' },
  { name: 'Polish', code: 'PL' }
])

p "Created #{Language.count} languages"

TranslationKey.destroy_all

translationKeys = TranslationKey.create([
  { key: 'ACTIONS' },
  { key: 'ASSIGNMENTS' },
  { key: 'CANCEL' },
  { key: 'CLASS-ROOM' },
  { key: 'CLASS-ROOMS' },
  { key: 'CLASS-TEACHER' },
  { key: 'CLASS-UNIT' },
  { key: 'CLASS-UNITS' },
  { key: 'CONNECTION-ERROR' },
  { key: 'CREATE' },
  { key: 'CREATED-AT' },
  { key: 'CREATOR-TITLE' },
  { key: 'DESIGNATION' },
  { key: 'EDIT' },
  { key: 'EDITOR-TITLE' },
  { key: 'EMAIL' },
  { key: 'EMAIL-BUSY' },
  { key: 'ENGLISH' },
  { key: 'ENTER-DESIGNATION' },
  { key: 'ENTER-EMAIL' },
  { key: 'ENTER-FIRST-NAME' },
  { key: 'ENTER-FLOOR' },
  { key: 'ENTER-LAST-NAME' },
  { key: 'ENTER-LOCATION' },
  { key: 'ENTER-NAME' },
  { key: 'ENTER-PASSWORD' },
  { key: 'ENTER-REPEAT-PASSWORD' },
  { key: 'ENTER-SHORT-NAME' },
  { key: 'ENTER-VALID-EMAIL' },
  { key: 'EXCUSES' },
  { key: 'FIELD-REQUIRED' },
  { key: 'FIRST-NAME' },
  { key: 'FLOOR' },
  { key: 'FRIDAY' },
  { key: 'INCORRECT-PASSWORD' },
  { key: 'ITEMS-PER-PAGE' },
  { key: 'LANGUAGE' },
  { key: 'LAST-NAME' },
  { key: 'LEGAL-GUARDIAN' },
  { key: 'LESSON-HOUR' },
  { key: 'LESSON-HOURS' },
  { key: 'LESSON-PLANS' },
  { key: 'LISTS-OF-TEACHERS-AND-SUBJECTS' },
  { key: 'LOCATION' },
  { key: 'MESSAGE' },
  { key: 'MIN-LENGTH' },
  { key: 'MONDAY' },
  { key: 'NAME' },
  { key: 'OF' },
  { key: 'PAGE' },
  { key: 'PASSWORD' },
  { key: 'PLAN-OF-LESSONS' },
  { key: 'POLISH' },
  { key: 'PRAISE-AND-ATTENTION' },
  { key: 'REMEMBER' },
  { key: 'REPEAT-PASSWORD' },
  { key: 'SAVE' },
  { key: 'SET-TIME-FROM' },
  { key: 'SET-TIME-TO' },
  { key: 'SHORT-NAME' },
  { key: 'STUDENT' },
  { key: 'SUBJECT' },
  { key: 'SUBJECTS' },
  { key: 'SUBMIT' },
  { key: 'SYSTEM-ADMINISTRATOR' },
  { key: 'TEACHER' },
  { key: 'THURSDAY' },
  { key: 'TIME-FROM' },
  { key: 'TIME-TO' },
  { key: 'TITLE' },
  { key: 'TUESDAY' },
  { key: 'UNEXPECTED-ERROR-OCCURRED' },
  { key: 'UPDATED-AT' },
  { key: 'USER-ALREADY-EXIST' },
  { key: 'USER-HAS-NOT-EXIST' },
  { key: 'USER-REGISTERED' },
  { key: 'USER-TYPE' },
  { key: 'USER-UNREGISTERED' },
  { key: 'WEDNESDAY' }
])

p "Created #{TranslationKey.count} keys of translations"

TranslationScope.destroy_all

translationScopes = TranslationScope.create([
  { name: 'SHARED' },
  { name: 'LOGIN' },
  { name: 'REGISTER' },
  { name: 'DASHBOARD' },
  { name: 'CONFIGURATION' },
  { name: 'CONFIGURATION-ASSIGNMENTS' },
  { name: 'CONFIGURATION-CLASS-ROOMS' },
  { name: 'CONFIGURATION-LESSON-HOURS' },
  { name: 'CONFIGURATION-LESSON-PLANS' },
  { name: 'CONFIGURATION-SUBJECTS' },
  { name: 'SETTINGS' },
  { name: 'VALIDATION' }
])

p "Created #{TranslationScope.count} scopes of translations"

Translation.destroy_all

Translation.create!([
  # SHARED
  { translation_key_id: translationKeys[0].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Actions' },
  { translation_key_id: translationKeys[0].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Akcje' },
  { translation_key_id: translationKeys[2].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Cancel' },
  { translation_key_id: translationKeys[2].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Anuluj' },
  { translation_key_id: translationKeys[6].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Class unit' },
  { translation_key_id: translationKeys[6].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Jednostka lekcyjna' },
  { translation_key_id: translationKeys[8].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Backend API connection issue, please contact...' },
  { translation_key_id: translationKeys[8].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Problem z połączeniem z API, proszę o kontakt...' },
  { translation_key_id: translationKeys[9].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Create' },
  { translation_key_id: translationKeys[9].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Utwórz' },
  { translation_key_id: translationKeys[10].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Created at' },
  { translation_key_id: translationKeys[10].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Data utworzenia' },
  { translation_key_id: translationKeys[13].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Edit' },
  { translation_key_id: translationKeys[13].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Edytuj' },
  { translation_key_id: translationKeys[15].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'E-mail' },
  { translation_key_id: translationKeys[15].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'E-mail' },
  { translation_key_id: translationKeys[17].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'English' },
  { translation_key_id: translationKeys[17].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Angielski' },
  { translation_key_id: translationKeys[19].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Enter e-mail' },
  { translation_key_id: translationKeys[19].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Wprowadź e-mail' },
  { translation_key_id: translationKeys[19].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Enter e-mail' },
  { translation_key_id: translationKeys[19].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Wprowadź e-mail' },
  { translation_key_id: translationKeys[24].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Enter name' },
  { translation_key_id: translationKeys[24].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Wprowadź nazwę' },
  { translation_key_id: translationKeys[24].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Enter name' },
  { translation_key_id: translationKeys[24].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Wprowadź nazwę' },
  { translation_key_id: translationKeys[25].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Enter password' },
  { translation_key_id: translationKeys[25].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Wprowadź hasło' },
  { translation_key_id: translationKeys[27].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Enter short name' },
  { translation_key_id: translationKeys[27].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Wprowadź skróconą nazwę' },
  { translation_key_id: translationKeys[33].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Friday' },
  { translation_key_id: translationKeys[33].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Piątek' },
  { translation_key_id: translationKeys[35].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Items per page' },
  { translation_key_id: translationKeys[35].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Elementów na stronie' },
  { translation_key_id: translationKeys[38].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Legal guardian' },
  { translation_key_id: translationKeys[38].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Opiekun prawny' },
  { translation_key_id: translationKeys[46].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Monday' },
  { translation_key_id: translationKeys[46].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Poniedziałek' },
  { translation_key_id: translationKeys[47].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Name' },
  { translation_key_id: translationKeys[47].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Nazwa' },
  { translation_key_id: translationKeys[48].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'of' },
  { translation_key_id: translationKeys[48].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'z' },
  { translation_key_id: translationKeys[49].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Page' },
  { translation_key_id: translationKeys[49].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Strona' },
  { translation_key_id: translationKeys[50].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Password' },
  { translation_key_id: translationKeys[50].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Hasło' },
  { translation_key_id: translationKeys[52].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Polish' },
  { translation_key_id: translationKeys[52].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Polski' },
  { translation_key_id: translationKeys[56].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Save' },
  { translation_key_id: translationKeys[56].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Zapisz' },
  { translation_key_id: translationKeys[59].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Short name' },
  { translation_key_id: translationKeys[59].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Skrócona nazwa' },
  { translation_key_id: translationKeys[60].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Student' },
  { translation_key_id: translationKeys[60].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Student' },
  { translation_key_id: translationKeys[64].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'System administrator' },
  { translation_key_id: translationKeys[64].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Administrator systemowy' },
  { translation_key_id: translationKeys[65].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Teacher' },
  { translation_key_id: translationKeys[65].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Nauczyciel' },
  { translation_key_id: translationKeys[66].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Thursday' },
  { translation_key_id: translationKeys[66].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Czwartek' },
  { translation_key_id: translationKeys[70].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Tuesday' },
  { translation_key_id: translationKeys[70].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Wtorek' },
  { translation_key_id: translationKeys[71].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Unexpected error occured' },
  { translation_key_id: translationKeys[71].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Nieznany problem' },
  { translation_key_id: translationKeys[72].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Updated at' },
  { translation_key_id: translationKeys[72].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Data aktualizacji' },
  { translation_key_id: translationKeys[73].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Użytkownik już istnieje' },
  { translation_key_id: translationKeys[73].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'User already exist' },
  { translation_key_id: translationKeys[74].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Użytkownik nie istnieje' },
  { translation_key_id: translationKeys[74].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'User has not exist' },
  { translation_key_id: translationKeys[75].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'User has been registered' },
  { translation_key_id: translationKeys[75].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Użytkownik został zarejestrowany' },
  { translation_key_id: translationKeys[78].id, language_id: languages[0].id, translation_scope_id: translationScopes[0].id, value: 'Wednesday' },
  { translation_key_id: translationKeys[78].id, language_id: languages[1].id, translation_scope_id: translationScopes[0].id, value: 'Środa' },
  # LOGIN
  { translation_key_id: translationKeys[34].id, language_id: languages[0].id, translation_scope_id: translationScopes[1].id, value: 'Incorrect password' },
  { translation_key_id: translationKeys[34].id, language_id: languages[1].id, translation_scope_id: translationScopes[1].id, value: 'Niepoprawne hasło' },
  { translation_key_id: translationKeys[44].id, language_id: languages[0].id, translation_scope_id: translationScopes[1].id, value: 'If you do not have an account, register!' },
  { translation_key_id: translationKeys[44].id, language_id: languages[1].id, translation_scope_id: translationScopes[1].id, value: 'Jeśli nie masz konta, zarejestruj się!' },
  { translation_key_id: translationKeys[63].id, language_id: languages[0].id, translation_scope_id: translationScopes[1].id, value: 'Log in!' },
  { translation_key_id: translationKeys[63].id, language_id: languages[1].id, translation_scope_id: translationScopes[1].id, value: 'Zaloguj się!' },
  { translation_key_id: translationKeys[69].id, language_id: languages[0].id, translation_scope_id: translationScopes[1].id, value: 'Log in' },
  { translation_key_id: translationKeys[69].id, language_id: languages[1].id, translation_scope_id: translationScopes[1].id, value: 'Logowanie' },
  { translation_key_id: translationKeys[77].id, language_id: languages[0].id, translation_scope_id: translationScopes[1].id, value: 'User has not been registered.' },
  { translation_key_id: translationKeys[77].id, language_id: languages[1].id, translation_scope_id: translationScopes[1].id, value: 'Użytkownik nie został zarejestrowany.' },
  # REGISTER
  { translation_key_id: translationKeys[16].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'E-mail is busy.' },
  { translation_key_id: translationKeys[16].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'E-mail zajęty.' },
  { translation_key_id: translationKeys[20].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Enter first name' },
  { translation_key_id: translationKeys[20].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Wprowadź imię' },
  { translation_key_id: translationKeys[22].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Enter last name' },
  { translation_key_id: translationKeys[22].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Wprowadź nazwisko' },
  { translation_key_id: translationKeys[31].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Enter repeat password' },
  { translation_key_id: translationKeys[31].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Wprowadź ponownie hasło' },
  { translation_key_id: translationKeys[32].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'First name' },
  { translation_key_id: translationKeys[32].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Imię' },
  { translation_key_id: translationKeys[44].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'If you already have an account, log in!' },
  { translation_key_id: translationKeys[44].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Jeśli już posiadasz konto, zaloguj się!' },
  { translation_key_id: translationKeys[47].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Last name' },
  { translation_key_id: translationKeys[47].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Nazwisko' },
  { translation_key_id: translationKeys[55].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Repeat password' },
  { translation_key_id: translationKeys[55].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Powtórz hasło' },
  { translation_key_id: translationKeys[63].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Register in!' },
  { translation_key_id: translationKeys[63].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Zarejestruj się!' },
  { translation_key_id: translationKeys[69].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Register' },
  { translation_key_id: translationKeys[69].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Rejestracja' },
  { translation_key_id: translationKeys[75].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'User has been registered.' },
  { translation_key_id: translationKeys[75].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Użytkownik został zarejestrowany.' },
  { translation_key_id: translationKeys[76].id, language_id: languages[0].id, translation_scope_id: translationScopes[2].id, value: 'Type of user' },
  { translation_key_id: translationKeys[76].id, language_id: languages[1].id, translation_scope_id: translationScopes[2].id, value: 'Typ użytkownika' },


  { translation_key_id: translationKeys[1].id, language_id: languages[0].id, translation_scope_id: translationScopes[4].id, value: 'Assignments' },
  { translation_key_id: translationKeys[1].id, language_id: languages[1].id, translation_scope_id: translationScopes[4].id, value: 'Przynależności' },
  { translation_key_id: translationKeys[3].id, language_id: languages[0].id, translation_scope_id: translationScopes[8].id, value: 'Class room' },
  { translation_key_id: translationKeys[3].id, language_id: languages[1].id, translation_scope_id: translationScopes[8].id, value: 'Sala lekcyjna' },
  { translation_key_id: translationKeys[4].id, language_id: languages[0].id, translation_scope_id: translationScopes[4].id, value: 'Class rooms' },
  { translation_key_id: translationKeys[4].id, language_id: languages[1].id, translation_scope_id: translationScopes[4].id, value: 'Sale lekcyjne' },
  { translation_key_id: translationKeys[5].id, language_id: languages[0].id, translation_scope_id: translationScopes[4].id, value: 'Class teacher' },
  { translation_key_id: translationKeys[5].id, language_id: languages[1].id, translation_scope_id: translationScopes[4].id, value: 'Wychowawca' },
])

p "Created #{Translation.count} translations"